import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/app/(home)/navigation";
import WrappedCorbadoProvider from "@/app/wrapped-corbado-provider";
import Link from "next/link";
import Image from "next/image";
import { getAuthenticatedUserFromCookie } from "@/lib/server/authentication";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // obtain user information, so we can pass it to the navigation bar
    // in a real-world application, you might store this information in a context
    const user = await getAuthenticatedUserFromCookie();
    const isAuthenticated = !!user;

    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <WrappedCorbadoProvider>
                    <Navigation initialIsAutenticated={isAuthenticated} />
                    <main>
                        <section>{children}</section>
                        <footer>
                            <Link
                                href="https://github.com/corbado/examples.git"
                                target="_blank"
                            >
                                <Image
                                    src="/github-icon.svg"
                                    alt="GitHub icon"
                                    width="24"
                                    height="24"
                                />
                                Github
                            </Link>
                            <Link
                                href="https://docs.corbado.com/corbado-complete/overview/welcome"
                                target="_blank"
                            >
                                <Image
                                    src="/documents-icon.svg"
                                    alt="Documentation icon"
                                    width="24"
                                    height="24"
                                />
                                Documentation
                            </Link>
                        </footer>
                    </main>
                </WrappedCorbadoProvider>
            </body>
        </html>
    );
}
